version: '3.3'

services:
    
    api:

        build: ./Docker/Node
        expose:
            - 80
        ports: 
            - "8000:80"
        working_dir: /app
        command: nodemon --legacy-watch src/index.js
        volumes:
            - .:/app
        environment: 
            - NODE_ENV=development
        depends_on: 
            - mongodb

    web_client:

        build: ./Docker/Parcel
        expose: 
            - 1234
            - 35585
        ports:
            - "8001:1234"
            - "35585:35585"
        volumes:
            - ./client:/app
        environment: 
            - NODE_ENV=development

        depends_on:
            - api
        

    minio1:
        image: minio/minio
        volumes:
            - minio_storage1:/export
        ports:
            - "9001:9000"
        environment:
            MINIO_ACCESS_KEY: super_secret
            MINIO_SECRET_KEY: super_secret
        command: server http://minio{1...4}/export
        depends_on: 
            - api

    minio3:
        image: minio/minio
        volumes:
            - minio_storage3:/export
        ports:
            - "9003:9000"
        environment:
            MINIO_ACCESS_KEY: super_secret
            MINIO_SECRET_KEY: super_secret
        command: server http://minio{1...4}/export
        depends_on: 
            - api

    minio4:
        image: minio/minio
        volumes:
            - minio_storage4:/export
        ports:
            - "9004:9000"
        environment:
            MINIO_ACCESS_KEY: super_secret
            MINIO_SECRET_KEY: super_secret
        command: server http://minio{1...4}/export
        depends_on: 
            - api

    mongodb:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - chatter_mongodb:/data/db
        command: mongod --smallfiles --logpath=/dev/null


volumes:
    minio_storage1:
    minio_storage2:
    minio_storage3:
    minio_storage4:
    chatter_mongodb:
